---
title: "Untitled"
author: "DJM"
date: '2022-06-06'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidymodels)
library(epiprocess)
# devtools::install_github("cmu-delphi/epipredict")
library(epipredict)
```

```{r small-data}
jhu <- case_death_rate_subset %>%
  filter(time_value > "2021-08-01") %>%
  dplyr::arrange(geo_value, time_value)

jhu_latest <- jhu %>%
  filter(!is.na(case_rate), !is.na(death_rate)) %>%
  group_by(geo_value) %>%
  slice_tail(n = 15) %>% # have lags 0,...,14, so need 15 for a complete case
  ungroup()
```

The recipe encodes how to process training/testing data. S3 object.

```{r recipe}
r <- epi_recipe(jhu) %>%
  step_epi_lag(death_rate, lag = c(0, 7, 14)) %>%
  step_epi_ahead(death_rate, ahead = 7) %>%
  step_epi_lag(case_rate, lag = c(0, 7, 14)) %>%
  step_naomit(all_predictors()) %>%
  step_naomit(all_outcomes(), skip = TRUE)
```

The workflow combines a recipe and a model specification. Fit, estimates
the model, adds the resulting object to the workflow.

```{r workflow}
wf <- epi_workflow(r, linear_reg()) %>% 
  fit(jhu)

wf
```

The workflow also has slots for post-processing. (Currently unimplemented.)

```{r workflow2}
names(wf) # 3 lists and a flag
```

Predict gives a new `epi_df`

```{r predict}
pp <- predict(wf, new_data = jhu_latest)
pp 
```

Can add a `forecast_date` (should be a post processing step)

```{r predict2}
# Want: 
# predict(wf, new_data = jhu_latest, forecast_date = "2021-12-31") %>%
#  filter(!is.na(.pred))

# Intended output:
predict(wf, new_data = jhu_latest) %>% 
  mutate(forecast_date = as.Date("2021-12-31")) %>% 
  filter(!is.na(.pred))
```


